/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'package:stackfrost/services/coins/bitcoin/bitcoin_wallet.dart' as btc;
import 'package:stackfrost/utilities/constants.dart';

enum Coin {
  bitcoin,
  bitcoinTestNet,
}

final int kTestNetCoinCount = 1; // Util.isDesktop ? 5 : 4;

extension CoinExt on Coin {
  String get prettyName {
    switch (this) {
      case Coin.bitcoin:
        return "Bitcoin";
      case Coin.bitcoinTestNet:
        return "tBitcoin";
    }
  }

  String get ticker {
    switch (this) {
      case Coin.bitcoin:
        return "BTC";
      case Coin.bitcoinTestNet:
        return "tBTC";
    }
  }

  String get uriScheme {
    switch (this) {
      case Coin.bitcoin:
        return "bitcoin";
      case Coin.bitcoinTestNet:
        return "bitcoin";
    }
  }

  bool get isElectrumXCoin {
    switch (this) {
      case Coin.bitcoin:
      case Coin.bitcoinTestNet:
        return true;
    }
  }

  bool get isTestNet {
    switch (this) {
      case Coin.bitcoin:
        return false;

      case Coin.bitcoinTestNet:
        return true;
    }
  }

  Coin get mainNetVersion {
    switch (this) {
      case Coin.bitcoin:
        return this;

      case Coin.bitcoinTestNet:
        return Coin.bitcoin;
    }
  }

  int get requiredConfirmations {
    switch (this) {
      case Coin.bitcoin:
      case Coin.bitcoinTestNet:
        return btc.MINIMUM_CONFIRMATIONS;
    }
  }

  int get decimals => Constants.decimalPlacesForCoin(this);
}

Coin coinFromPrettyName(String name) {
  switch (name) {
    case "Bitcoin":
    case "bitcoin":
      return Coin.bitcoin;

    case "Bitcoin Testnet":
    case "tBitcoin":
    case "bitcoinTestNet":
      return Coin.bitcoinTestNet;

    default:
      throw ArgumentError.value(
        name,
        "name",
        "No Coin enum value with that prettyName",
      );
  }
}

Coin coinFromTickerCaseInsensitive(String ticker) {
  switch (ticker.toLowerCase()) {
    case "btc":
      return Coin.bitcoin;
    case "tbtc":
      return Coin.bitcoinTestNet;
    default:
      throw ArgumentError.value(
          ticker, "name", "No Coin enum value with that ticker");
  }
}
