/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_svg/svg.dart';
import 'package:stackfrost/models/isar/exchange_cache/currency.dart';
import 'package:stackfrost/themes/coin_icon_provider.dart';
import 'package:stackfrost/themes/stack_colors.dart';
import 'package:stackfrost/utilities/constants.dart';
import 'package:stackfrost/utilities/enums/coin_enum.dart';

class WalletInfoCoinIcon extends ConsumerWidget {
  const WalletInfoCoinIcon({
    Key? key,
    required this.coin,
    this.size = 32,
    this.contractAddress,
  }) : super(key: key);

  final Coin coin;
  final String? contractAddress;
  final double size;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    Currency? currency;

    return Container(
      width: size,
      height: size,
      decoration: BoxDecoration(
        color: Theme.of(context)
            .extension<StackColors>()!
            .colorForCoin(coin)
            .withOpacity(0.4),
        borderRadius: BorderRadius.circular(
          Constants.size.circularBorderRadius,
        ),
      ),
      child: Padding(
        padding: EdgeInsets.all(size / 5),
        child: currency != null && currency.image.isNotEmpty
            ? SvgPicture.network(
                currency.image,
                width: 20,
                height: 20,
              )
            : SvgPicture.file(
                File(
                  ref.watch(coinIconProvider(coin)),
                ),
                width: 20,
                height: 20,
              ),
      ),
    );
  }
}
