/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'dart:io';

import 'package:flutter/material.dart';
import 'package:stackfrost/pages/settings_views/global_settings_view/advanced_views/advanced_settings_view.dart';
import 'package:stackfrost/pages/settings_views/global_settings_view/delete_account_view.dart';
import 'package:stackfrost/pages/settings_views/global_settings_view/manage_nodes_views/manage_nodes_view.dart';
import 'package:stackfrost/pages/settings_views/global_settings_view/security_views/security_view.dart';
import 'package:stackfrost/pages/settings_views/sub_widgets/settings_list_button.dart';
import 'package:stackfrost/themes/stack_colors.dart';
import 'package:stackfrost/utilities/assets.dart';
import 'package:stackfrost/utilities/text_styles.dart';
import 'package:stackfrost/widgets/background.dart';
import 'package:stackfrost/widgets/custom_buttons/app_bar_icon_button.dart';
import 'package:stackfrost/widgets/rounded_white_container.dart';

class GlobalSettingsView extends StatelessWidget {
  const GlobalSettingsView({
    Key? key,
  }) : super(key: key);

  static const String routeName = "/globalSettings";

  @override
  Widget build(BuildContext context) {
    debugPrint("BUILD: $runtimeType");
    return Background(
      child: Scaffold(
        backgroundColor: Theme.of(context).extension<StackColors>()!.background,
        appBar: AppBar(
          leading: AppBarBackButton(
            onPressed: () {
              Navigator.of(context).pop();
            },
          ),
          title: Text(
            "Settings",
            style: STextStyles.navBarTitle(context),
          ),
        ),
        body: LayoutBuilder(
          builder: (builderContext, constraints) {
            return Padding(
              padding: const EdgeInsets.only(
                left: 12,
                top: 12,
                right: 12,
              ),
              child: SingleChildScrollView(
                child: ConstrainedBox(
                  constraints: BoxConstraints(
                    minHeight: constraints.maxHeight - 24,
                  ),
                  child: IntrinsicHeight(
                    child: Padding(
                      padding: const EdgeInsets.all(4),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.stretch,
                        children: [
                          RoundedWhiteContainer(
                            padding: const EdgeInsets.all(4),
                            child: Column(
                              children: [
                                SettingsListButton(
                                  iconAssetName: Assets.svg.lock,
                                  iconSize: 16,
                                  title: "Security",
                                  onPressed: () {
                                    Navigator.of(context)
                                        .pushNamed(SecurityView.routeName);
                                  },
                                ),
                                const SizedBox(
                                  height: 8,
                                ),
                                SettingsListButton(
                                  iconAssetName: Assets.svg.node,
                                  iconSize: 16,
                                  title: "Manage nodes",
                                  onPressed: () {
                                    Navigator.of(context)
                                        .pushNamed(ManageNodesView.routeName);
                                  },
                                ),
                                // const SizedBox(
                                //   height: 8,
                                // ),
                                // SettingsListButton(
                                //   iconAssetName: Assets.svg.sun,
                                //   iconSize: 18,
                                //   title: "Appearance",
                                //   onPressed: () {
                                //     Navigator.of(context).pushNamed(
                                //       AppearanceSettingsView.routeName,
                                //     );
                                //   },
                                // ),
                                if (Platform.isIOS)
                                  const SizedBox(
                                    height: 8,
                                  ),
                                if (Platform.isIOS)
                                  SettingsListButton(
                                    iconAssetName: Assets.svg.circleAlert,
                                    iconSize: 16,
                                    title: "Delete account",
                                    onPressed: () async {
                                      await Navigator.of(context).pushNamed(
                                          DeleteAccountView.routeName);
                                    },
                                  ),
                                // const SizedBox(
                                //   height: 8,
                                // ),
                                // SettingsListButton(
                                //   iconAssetName: Assets.svg.ellipsis,
                                //   iconSize: 18,
                                //   title: "About",
                                //   onPressed: () {
                                //     Navigator.of(context)
                                //         .pushNamed(AboutView.routeName);
                                //   },
                                // ),
                                const SizedBox(
                                  height: 8,
                                ),
                                SettingsListButton(
                                  iconAssetName: Assets.svg.solidSliders,
                                  iconSize: 16,
                                  title: "Advanced",
                                  onPressed: () {
                                    Navigator.of(context).pushNamed(
                                        AdvancedSettingsView.routeName);
                                  },
                                ),
                                // TextButton(
                                //   style: Theme.of(context)
                                //       .textButtonTheme
                                //       .style
                                //       ?.copyWith(
                                //         backgroundColor:
                                //             MaterialStateProperty.all<Color>(
                                //           Theme.of(context).extension<StackColors>()!.accentColorDark
                                //         ),
                                //       ),
                                //   child: Text(
                                //     "fire test notification",
                                //     style: STextStyles.button(context),
                                //   ),
                                //   onPressed: () async {
                                //     NotificationApi.showNotification2(
                                //       title: "Test notification",
                                //       body: "My doggy wallet",
                                //       walletId:
                                //           "3c5e2d70-fcc3-11ec-86a3-31a106a81c3b",
                                //       iconAssetName:
                                //           Assets.svg.iconFor(coin: Coin.dogecoin),
                                //       date: DateTime.now(),
                                //     );
                                //   },
                                // ),
                              ],
                            ),
                          ),
                          const SizedBox(
                            height: 12,
                          ),
                        ],
                      ),
                    ),
                  ),
                ),
              ),
            );
          },
        ),
      ),
    );
  }
}
