/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'package:equatable/equatable.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:stackwallet/services/coins/manager.dart';

class ContractWalletId implements Equatable {
  final String walletId;
  final String tokenContractAddress;

  ContractWalletId({
    required this.walletId,
    required this.tokenContractAddress,
  });

  @override
  List<Object?> get props => [walletId, tokenContractAddress];

  @override
  bool? get stringify => true;
}

/// provide the wallet for a given wallet id
final walletProvider =
    ChangeNotifierProvider.family<Manager?, String>((ref, arg) => null);
