// /*
//  * This file is part of Stack Wallet.
//  *
//  * Copyright (c) 2023 Cypher Stack
//  * All Rights Reserved.
//  * The code is distributed under GPLv3 license, see LICENSE file for details.
//  * Generated by Cypher Stack on 2023-05-26
//  *
//  */
//
// import 'package:flutter/material.dart';
// import 'package:flutter_riverpod/flutter_riverpod.dart';
// import 'package:stackfrost/pages/settings_views/global_settings_view/syncing_preferences_views/syncing_options_view.dart';
// import 'package:stackfrost/themes/stack_colors.dart';
// import 'package:stackfrost/utilities/constants.dart';
// import 'package:stackfrost/utilities/enums/sync_type_enum.dart';
// import 'package:stackfrost/utilities/text_styles.dart';
// import 'package:stackfrost/widgets/background.dart';
// import 'package:stackfrost/widgets/custom_buttons/app_bar_icon_button.dart';
// import 'package:stackfrost/widgets/rounded_white_container.dart';
//
// import '../../../../providers/global/prefs_provider.dart';
//
// class SyncingPreferencesView extends ConsumerWidget {
//   const SyncingPreferencesView({Key? key}) : super(key: key);
//
//   static const String routeName = "/syncingPreferences";
//
//   String _currentTypeDescription(SyncingType type) {
//     switch (type) {
//       case SyncingType.currentWalletOnly:
//         return "Sync only currently open wallet";
//       case SyncingType.selectedWalletsAtStartup:
//         return "Sync only selected wallets at startup";
//       case SyncingType.allWalletsOnStartup:
//         return "Sync all wallets at startup";
//     }
//   }
//
//   @override
//   Widget build(BuildContext context, WidgetRef ref) {
//     return Background(
//       child: Scaffold(
//         backgroundColor: Theme.of(context).extension<StackColors>()!.background,
//         appBar: AppBar(
//           leading: AppBarBackButton(
//             onPressed: () async {
//               Navigator.of(context).pop();
//             },
//           ),
//           title: Text(
//             "Syncing preferences",
//             style: STextStyles.navBarTitle(context),
//           ),
//         ),
//         body: Padding(
//           padding: const EdgeInsets.all(16),
//           child: LayoutBuilder(
//             builder: (context, constraints) {
//               return SingleChildScrollView(
//                 child: ConstrainedBox(
//                   constraints: BoxConstraints(
//                     minHeight: constraints.maxHeight,
//                   ),
//                   child: IntrinsicHeight(
//                     child: Column(
//                       crossAxisAlignment: CrossAxisAlignment.stretch,
//                       children: [
//                         RoundedWhiteContainer(
//                           padding: const EdgeInsets.all(0),
//                           child: RawMaterialButton(
//                             // splashColor: Theme.of(context).extension<StackColors>()!.highlight,
//                             padding: const EdgeInsets.all(0),
//                             materialTapTargetSize:
//                                 MaterialTapTargetSize.shrinkWrap,
//                             shape: RoundedRectangleBorder(
//                               borderRadius: BorderRadius.circular(
//                                 Constants.size.circularBorderRadius,
//                               ),
//                             ),
//                             onPressed: () {
//                               Navigator.of(context)
//                                   .pushNamed(SyncingOptionsView.routeName);
//                             },
//                             child: Padding(
//                               padding: const EdgeInsets.all(12),
//                               child: Row(
//                                 children: [
//                                   Column(
//                                     crossAxisAlignment:
//                                         CrossAxisAlignment.start,
//                                     children: [
//                                       //     Text(
//                                       //       "Syncing",
//                                       //       style: STextStyles.titleBold12(context),
//                                       //       textAlign: TextAlign.left,
//                                       //     ),
//                                       Text(
//                                         _currentTypeDescription(ref
//                                             .read(prefsChangeNotifierProvider)
//                                             .syncType),
//                                         style:
//                                             STextStyles.itemSubtitle(context),
//                                         textAlign: TextAlign.left,
//                                       )
//                                     ],
//                                   ),
//                                   const Spacer(),
//                                 ],
//                               ),
//                             ),
//                           ),
//                         ),
//                         const SizedBox(
//                           height: 8,
//                         ),
//                         RoundedWhiteContainer(
//                           child: Consumer(
//                             builder: (_, ref, __) {
//                               return RawMaterialButton(
//                                 // splashColor: Theme.of(context).extension<StackColors>()!.highlight,
//                                 materialTapTargetSize:
//                                     MaterialTapTargetSize.shrinkWrap,
//                                 shape: RoundedRectangleBorder(
//                                   borderRadius: BorderRadius.circular(
//                                     Constants.size.circularBorderRadius,
//                                   ),
//                                 ),
//                                 onPressed: null,
//                                 child: Padding(
//                                   padding:
//                                       const EdgeInsets.symmetric(vertical: 8),
//                                   child: Row(
//                                     mainAxisAlignment:
//                                         MainAxisAlignment.spaceBetween,
//                                     children: [
//                                       Text(
//                                         "AutoSync only on Wi-Fi",
//                                         style: STextStyles.titleBold12(context),
//                                         textAlign: TextAlign.left,
//                                       ),
//
//                                     ],
//                                   ),
//                                 ),
//                               );
//                             },
//                           ),
//                         ),
//                       ],
//                     ),
//                   ),
//                 ),
//               );
//             },
//           ),
//         ),
//       ),
//     );
//   }
// }
