// /*
//  * This file is part of Stack Wallet.
//  *
//  * Copyright (c) 2023 Cypher Stack
//  * All Rights Reserved.
//  * The code is distributed under GPLv3 license, see LICENSE file for details.
//  * Generated by Cypher Stack on 2023-05-26
//  *
//  */
//
// import 'dart:io';
//
// import 'package:decimal/decimal.dart';
// import 'package:flutter/cupertino.dart';
// import 'package:flutter_riverpod/flutter_riverpod.dart';
// import 'package:flutter_svg/svg.dart';
// import 'package:stackfrost/models/exchange/response_objects/trade.dart';
// import 'package:stackfrost/models/isar/stack_theme.dart';
// import 'package:stackfrost/themes/theme_providers.dart';
// import 'package:stackfrost/utilities/format.dart';
// import 'package:stackfrost/utilities/text_styles.dart';
// import 'package:stackfrost/utilities/util.dart';
// import 'package:stackfrost/widgets/conditional_parent.dart';
// import 'package:stackfrost/widgets/rounded_white_container.dart';
//
// class TradeCard extends ConsumerWidget {
//   const TradeCard({
//     Key? key,
//     required this.trade,
//     required this.onTap,
//   }) : super(key: key);
//
//   final Trade trade;
//   final VoidCallback onTap;
//
//   @override
//   Widget build(BuildContext context, WidgetRef ref) {
//     final isDesktop = Util.isDesktop;
//
//     return ConditionalParent(
//       condition: isDesktop,
//       builder: (child) => MouseRegion(
//         cursor: SystemMouseCursors.click,
//         child: child,
//       ),
//       child: GestureDetector(
//         onTap: onTap,
//         child: RoundedWhiteContainer(
//           padding:
//               isDesktop ? const EdgeInsets.all(16) : const EdgeInsets.all(12),
//           child: Row(
//             children: [
//               Expanded(
//                 child: Column(
//                   children: [
//                     Row(
//                       mainAxisAlignment: MainAxisAlignment.spaceBetween,
//                       children: [
//                         Text(
//                           "${trade.payInCurrency.toUpperCase()} → ${trade.payOutCurrency.toUpperCase()}",
//                           style: STextStyles.itemSubtitle12(context),
//                         ),
//                         Text(
//                           "${isDesktop ? "-" : ""}${Decimal.tryParse(trade.payInAmount) ?? "..."} ${trade.payInCurrency.toUpperCase()}",
//                           style: STextStyles.itemSubtitle12(context),
//                         ),
//                       ],
//                     ),
//                     const SizedBox(
//                       height: 2,
//                     ),
//                     Row(
//                       mainAxisAlignment: MainAxisAlignment.spaceBetween,
//                       children: [
//                         if (!isDesktop)
//                           Text(
//                             trade.exchangeName,
//                             style: STextStyles.label(context),
//                           ),
//                         Text(
//                           Format.extractDateFrom(
//                               trade.timestamp.millisecondsSinceEpoch ~/ 1000),
//                           style: STextStyles.label(context),
//                         ),
//                         if (isDesktop)
//                           Text(
//                             trade.exchangeName,
//                             style: STextStyles.label(context),
//                           ),
//                       ],
//                     ),
//                   ],
//                 ),
//               )
//             ],
//           ),
//         ),
//       ),
//     );
//   }
// }
