/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:stackfrost/pages/send_view/frost_ms/frost_import_sign_config_view.dart';
import 'package:stackfrost/pages/send_view/frost_ms/frost_send_view.dart';
import 'package:stackfrost/pages_desktop_specific/my_stack_view/wallet_view/sub_widgets/desktop_receive.dart';
import 'package:stackfrost/pages_desktop_specific/my_stack_view/wallet_view/sub_widgets/desktop_send.dart';
import 'package:stackfrost/providers/global/wallets_provider.dart';
import 'package:stackfrost/utilities/enums/coin_enum.dart';
import 'package:stackfrost/widgets/custom_tab_view.dart';
import 'package:stackfrost/widgets/desktop/secondary_button.dart';
import 'package:stackfrost/widgets/rounded_white_container.dart';

class MyWallet extends ConsumerStatefulWidget {
  const MyWallet({
    Key? key,
    required this.walletId,
  }) : super(key: key);

  final String walletId;

  @override
  ConsumerState<MyWallet> createState() => _MyWalletState();
}

class _MyWalletState extends ConsumerState<MyWallet> {
  final titles = [
    "Send",
    "Receive",
  ];

  late final bool isFrost;
  late final Coin coin;

  @override
  void initState() {
    isFrost = ref
        .read(walletsChangeNotifierProvider)
        .getManager(widget.walletId)
        .isFrostMS;
    coin = ref
        .read(walletsChangeNotifierProvider)
        .getManager(widget.walletId)
        .coin;
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return ListView(
      primary: false,
      children: [
        RoundedWhiteContainer(
          padding: EdgeInsets.zero,
          child: CustomTabView(
            titles: titles,
            children: [
              Padding(
                padding: const EdgeInsets.all(20),
                child: isFrost
                    ? Column(
                        children: [
                          Row(
                            mainAxisAlignment: MainAxisAlignment.end,
                            children: [
                              SecondaryButton(
                                width: 200,
                                buttonHeight: ButtonHeight.l,
                                label: "Import sign config",
                                onPressed: () {
                                  Navigator.of(context).pushNamed(
                                    FrostImportSignConfigView.routeName,
                                    arguments: widget.walletId,
                                  );
                                },
                              ),
                            ],
                          ),
                          FrostSendView(
                            walletId: widget.walletId,
                            coin: coin,
                          ),
                        ],
                      )
                    : DesktopSend(
                        walletId: widget.walletId,
                      ),
              ),
              Padding(
                padding: const EdgeInsets.all(20),
                child: DesktopReceive(
                  walletId: widget.walletId,
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
