/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'package:flutter/material.dart';
import 'package:stackfrost/utilities/enums/coin_enum.dart';

const kCoinThemeColorDefaults = CoinThemeColorDefault();

class CoinThemeColorDefault {
  const CoinThemeColorDefault();

  Color get bitcoin => const Color(0xFFFCC17B);

  Color forCoin(Coin coin) {
    switch (coin) {
      case Coin.bitcoin:
      case Coin.bitcoinTestNet:
        return bitcoin;
    }
  }
}
